name: stock_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio: 5.1.1
  http: 0.13.5
  get_storage: 2.1.1
  # intl: 0.18.1
  intl: 0.17.0
  google_fonts: ^3.0.1
  fl_chart: ^0.40.0
  plugin_platform_interface: ^2.1.2
  url_launcher: ^6.0.0
  flutter_datetime_picker: ^1.5.1
  

  flutter:
    sdk: flutter
  candlesticks: ^2.1.0
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.3
  native_notify: ^0.0.3
  midtrans_sdk: ^0.3.4
  flutter_dotenv: ^5.1.0
  firebase_storage: ^11.2.4
  image_picker: ^1.0.1
  flutter_local_notifications: ^15.1.0+1
  flutter_bloc: ^8.1.3
  webview_flutter: ^4.2.2
  dropdown_search: ^5.0.6
  dropdown_textfield: ^1.0.8
  cloud_firestore: ^4.8.3
  interactive_chart: ^0.3.4
  syncfusion_flutter_charts: ^21.2.4
  mobx: ^2.2.0
  flutter_launcher_icons: ^0.9.3
  multi_select_flutter: ^4.1.3
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  
  image_path: "assets/images/logo-final.png"
  
  android: true
  ios: true
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/

