// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh1UUrjKgSza6iNhN49n9m-v7UCdC4TEw',
    appId: '1:212749305920:web:6b3b4919244c95d3a237a5',
    messagingSenderId: '212749305920',
    projectId: 'stockapp-flutter',
    authDomain: 'stockapp-flutter.firebaseapp.com',
    storageBucket: 'stockapp-flutter.appspot.com',
    measurementId: 'G-FSM9ED48ER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3bq-m8HxqQSCzg0ByjYZCBWpHWPRfpKc',
    appId: '1:212749305920:android:dbcc98b02b1351d9a237a5',
    messagingSenderId: '212749305920',
    projectId: 'stockapp-flutter',
    storageBucket: 'stockapp-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkZfPt_BY-edJo9oyjhgHYuihNxCrQnNU',
    appId: '1:212749305920:ios:1066239b777e1bc2a237a5',
    messagingSenderId: '212749305920',
    projectId: 'stockapp-flutter',
    storageBucket: 'stockapp-flutter.appspot.com',
    iosClientId: '212749305920-3cps361ght4r5rl78gbapl02n50h6e6g.apps.googleusercontent.com',
    iosBundleId: 'com.stockapp.stockApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkZfPt_BY-edJo9oyjhgHYuihNxCrQnNU',
    appId: '1:212749305920:ios:1066239b777e1bc2a237a5',
    messagingSenderId: '212749305920',
    projectId: 'stockapp-flutter',
    storageBucket: 'stockapp-flutter.appspot.com',
    iosClientId: '212749305920-3cps361ght4r5rl78gbapl02n50h6e6g.apps.googleusercontent.com',
    iosBundleId: 'com.stockapp.stockApp',
  );
}
